export enum LogicBlockType {
  SET_VARIABLE = 'Set variable',
  CONDITION = 'Condition',
  REDIRECT = 'Redirect',
  SCRIPT = 'Code',
  TYPEBOT_LINK = 'Typebot link',
  WAIT = 'Wait',
  TRANSFER = 'Transfer',
  SPREAD = 'Spread',
  TAG = 'Tag',
  REMOVE_TAG = 'Remove tag',
  END = 'End',
  JUMP = 'Jump',
  AB_TEST = 'AB test',
  TEMPLATE = 'TemplateWABA',
  UPDATE_SYSTEM_NAME = 'Update system name',
  SEND_FROM = 'Send from',
  COMBINE_MESSAGES = 'Combine messages',
  AI_ASSISTANT = 'Ai assistant',
  TRANSCRIBE_AUDIO = 'Transcribe audio',
}
